# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f6a4aeed11e5b2721c7dff2a0116b3366ec8a1c2550743cb2c117b19b146f7372ecabcaed9e352f07a4a20179bec40cee175bc181f4c800baf585db764ac654

test:
  secret_key_base: cd1f443eb3c874049ea17719d3c2eb92441f20c1de17a3bfc2b189edc8719a51adb065087ddda2b4931e2e976c46de7b8058e0dd107cd0dd91bcfe4e377adf75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
